spring.application.name=Intel_Ta_Dsp
server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/kebiao
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.lty.www.kebiao.entity
mybatis.configuration.map-underscore-to-camel-case=true


logging.level.org.springframework.security=DEBUG

# src/main/resources/application.properties
deepseek.api-key=sk-813e807674cf45dea4d4111afa007063
deepseek.base-url=https://api.deepseek.com


